crate_type = "bin"

# For Cargo the license must be an SPDX 2.1 license expression identifier. Here we let the user choose the SPDX 2.1
# license identifier for one of the "popular licenses" listed on opensource.org, or "None".
# See:
#   - https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
#   - https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing
#   - https://opensource.org/licenses 
[license]
type = "list"
description = "Which license should your project have?"
values = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "GPL-2.0",
  "GPL-3.0",
  "LGPL-2.0",
  "LGPL-2.1",
  "LGPL-3.0",
  "MIT",
  "MPL-2.0",
  "CDDL-1.0",
  "EPL-2.0",
  "None"
]
default = "BSD-3-Clause"

[package_types]
type = "multi_list"
description = "Which package types should be built?"
values = [ "deb", "rpm", "docker" ]
default = [ "deb", "rpm", "docker" ]

[docker_org]
type = "string"
description = "Your Docker organization"
condition = "{{ 'docker' in package_types }}"
validator.regex = "^[a-z0-9]{2,}(?:[._-][a-z0-9]+)*$"

[docker_repo]
type = "string"
description = "Your Docker repository"
condition = "{{ 'docker' in package_types }}"
validator.regex = "^[a-z0-9]{2,}(?:[._-][a-z0-9]+)*$"

[docker_publish_user]
type = "string"
description = "Your Docker username for publishing (None to skip publishing, remember to set secret DOCKER_HUB_TOKEN to the access token from https://hub.docker.com/settings/security)"
condition = "{{ 'docker' in package_types }}"
default = "None"

[cross_targets]
type = "multi_list"
description = "Which targets (in addition to x86_64) should be compiled for?"
values = ["Raspberry Pi 1b", "Raspberry Pi 4b", "Rock 64"]
default = []

[[ignore]]
paths = ["Dockerfile"]
condition = "{{ 'docker' not in package_types }}"
