name: "pkg"

on:
  push:
  workflow_dispatch:

jobs:
  pkg:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v5
    {%- if docker_publish_user | default(value='None') != 'None' %}
    secrets:
      DOCKER_HUB_ID: {{ docker_publish_user }}
      DOCKER_HUB_TOKEN: {% raw -%}${{{%- endraw %} secrets.DOCKER_HUB_TOKEN {% raw -%}}}{%- endraw -%}
    {%- endif %}
    with:
      {%- if 'docker' in package_types %}
      docker_org: {{ docker_org }}
      docker_repo: {{ docker_repo }}
      docker_build_rules: |
        include:
          - platform:  "linux/amd64"
            shortname: "amd64"
            mode: "build"
          {%- if 'Raspberry Pi 1b' in cross_targets %}
          # Raspberry Pi 1b
          - platform:  "linux/arm/v6"
            shortname: "armv6"
            target:    "arm-unknown-linux-musleabihf"
            mode:      "copy"
          {%- endif %}
          {%- if 'Raspberry Pi 4b' in cross_targets %}
          # Raspberry Pi 4b
          - platform:  "linux/arm/v7"
            shortname: "armv7"
            target:    "armv7-unknown-linux-musleabihf"
            mode:      "copy"
          {%- endif %}
          {%- if 'Rock 64' in cross_targets %}
          # Rock 64
          - platform:  "linux/arm64"
            shortname: "arm64"
            target:    "aarch64-unknown-linux-musl"
            mode:      "copy"
          {%- endif %}
      {% endif %}

      {%- if 'deb' in package_types or 'rpm' in package_types %}
      package_build_rules: |
        image:
          {%- if 'deb' in package_types %}
          - "ubuntu:xenial"
          - "ubuntu:bionic"
          - "ubuntu:focal"
          - "ubuntu:jammy"  
          - "debian:stretch"
          - "debian:buster"
          - "debian:bullseye"
          {%- endif %}
          {%- if 'rpm' in package_types %}
          - "centos:7"
          - "centos:8"
          {%- endif %}
        target: x86_64
        {%- if cross_targets | length > 0 %}
        include:
        {%- endif -%}
          {%- if 'Raspberry Pi 1b' in cross_targets %}
          # Raspberry Pi 1b
          - image: "debian:buster"
            target: arm-unknown-linux-musleabihf
          {%- endif %}
          {%- if 'Raspberry Pi 4b' in cross_targets %}
          # Raspberry Pi 4b
          - image: "debian:bullseye"
            target: armv7-unknown-linux-musleabihf
          {%- endif %}
          {%- if 'Rock 64' in cross_targets %}
          # Rock 64
          - image: "debian:buster"
            target: aarch64-unknown-linux-musl
          {%- endif %}
      {%- endif %}
